# Generated by Django 5.1 on 2024-09-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table='Status',
        ),
    ]
