# Generated by Django 5.1 on 2024-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_status_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
    ]
