# Generated by Django 5.1 on 2024-10-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_alter_status_options_alter_status_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id'], 'verbose_name': 'Status'},
        ),
    ]
