# Generated by Django 5.1 on 2024-10-16 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_alter_label_options'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabels',
            name='labels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='label.label'),
        ),
        migrations.AlterField(
            model_name='tasklabels',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
