# Generated by Django 5.1 on 2024-09-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0007_remove_task_labels_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, default='', related_name='labels', to='label.label', verbose_name='Метки'),
        ),
    ]
