# Generated by Django 5.1 on 2024-10-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_alter_label_options_alter_label_name'),
        ('task', '0009_alter_task_options_alter_task_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='labels',
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='label', to='label.label', verbose_name='Label'),
        ),
    ]
