# Generated by Django 5.1 on 2024-10-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_alter_label_options_alter_label_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['id'], 'verbose_name': 'Label'},
        ),
    ]
